"""`devassist docs <path>` — generate a DOCS.md file summarising the project."""

import os
import re
from datetime import datetime

from .tree import tree_lines, iter_source_files


def cmd_docs(path):
    """Generate a DOCS.md file summarising the project."""
    if not os.path.isdir(path):
        print(f"Error: '{path}' is not a directory.")
        return

    output_path = os.path.join(path, "DOCS.md")
    lines_out = []

    project_name = os.path.basename(os.path.abspath(path))
    lines_out.append(f"# {project_name} — Auto-generated Documentation\n\n")
    lines_out.append(f"_Generated by DevAssist on {datetime.now().strftime('%Y-%m-%d %H:%M')}_\n\n")
    lines_out.append("---\n\n## Project Structure\n\n```\n")

    for line in tree_lines(path, exclude_files={"DOCS.md"}):
        lines_out.append(f"  {line}\n")

    lines_out.append("```\n\n---\n\n## File Summaries\n\n")

    for rel_path, abs_path in iter_source_files(path):
        with open(abs_path, encoding="utf-8", errors="replace") as f:
            src_lines = f.readlines()

        functions = [l.strip() for l in src_lines if re.match(r"\s*def ", l)]
        classes = [l.strip() for l in src_lines if re.match(r"\s*class ", l)]

        lines_out.append(f"### `{rel_path}`\n\n")
        lines_out.append(f"- **Lines:** {len(src_lines)}\n")
        lines_out.append(f"- **Classes:** {len(classes)}\n")
        lines_out.append(f"- **Functions:** {len(functions)}\n")

        if classes:
            names = ", ".join(c.replace("class ", "").split("(")[0].strip() for c in classes)
            lines_out.append(f"- **Defined classes:** {names}\n")
        if functions:
            names = ", ".join(f.replace("def ", "").split("(")[0].strip() for f in functions)
            lines_out.append(f"- **Defined functions:** {names}\n")

        lines_out.append("\n")

    with open(output_path, "w", encoding="utf-8") as f:
        f.writelines(lines_out)

    print(f"\n📝 Documentation written to: {output_path}\n")
